using Newtonsoft.Json;
using System;
using System.IO;
using System.Text.RegularExpressions;

namespace mre.model
{
	/// <summary>
	/// 生成 Minecraft 资源包的 pack.mcmeta 描述文件。
	/// 让提取出的资源目录能被 Minecraft 直接当作资源包加载。
	/// pack_format 通过版本号区间比较得出，覆盖从 1.6.1 到 1.21.8；
	/// 1.21.9 起资源包改用 min_format / max_format 新格式。数值参考 Minecraft Wiki 的 Pack format 表。
	/// </summary>
	public static class PackMcMeta
	{
		/// <summary>默认目标版本（无法自动检测时使用）</summary>
		public const string DefaultVersion = "1.20.1";

		/// <summary>默认资源包描述</summary>
		public const string DefaultDescription = "Generated by Minecraft Resource Extractor";

		/// <summary>下拉框快捷版本（常用 mod 版本）</summary>
		public static readonly string[] SupportedVersions =
		{
			"1.7.10", "1.8.9", "1.12.2", "1.14.4", "1.15.2", "1.16.5", "1.17.1", "1.18.2",
			"1.19.2", "1.19.4", "1.20.1", "1.20.2", "1.20.4", "1.21.1", "1.21.4", "1.21.5",
			"1.21.6", "1.21.7", "1.21.8"
		};

		/// <summary>匹配 1.x 或 1.x.y 形式的 MC 版本号</summary>
		private static readonly Regex McVersionRegex = new Regex(@"1\.\d+(?:\.\d+)?", RegexOptions.Compiled);

		/// <summary>1.21.9 起资源包改用 min_format / max_format（不再用单一 pack_format）</summary>
		private static readonly Version NewSchemaVersion = new Version(1, 21, 9);

		/// <summary>新 schema 的起始 format（对应 1.21.9）</summary>
		private const int NewSchemaMinFormat = 65;

		/// <summary>
		/// 从 jar 文件名（或任意文本）自动检测 MC 版本号。
		/// 如 "crreforged-1.0.0-forge-1.20.1-b10.jar" → "1.20.1"。
		/// 取最后一个匹配的 1.x[.y]（mod 命名约定中 MC 版本通常靠后）。检测不到返回 null。
		/// </summary>
		public static string DetectMcVersion(string text)
		{
			if (string.IsNullOrEmpty(text))
				return null;

			var matches = McVersionRegex.Matches(text);
			if (matches.Count == 0)
				return null;
			return matches[matches.Count - 1].Value;
		}

		/// <summary>
		/// 解析 MC 版本字符串（如 "1.20.1" 或 "1.20.1-forge"）→ pack_format。
		/// 用区间比较覆盖所有版本；无法解析时返回默认版本对应的 format。
		/// </summary>
		public static int GetPackFormat(string mcVersion)
		{
			if (TryParseVersion(mcVersion, out Version v))
				return FormatFor(v);
			return FormatFor(new Version(1, 20, 1));
		}

		/// <summary>返回用于日志/提示的格式描述（区分旧 pack_format 与新 min_format）</summary>
		public static string DescribeFormat(string mcVersion)
		{
			if (TryParseVersion(mcVersion, out Version v) && UsesNewSchema(v))
				return "min_format " + NewSchemaMinFormat + "（1.21.9+ 新格式）";
			return "pack_format " + GetPackFormat(mcVersion);
		}

		private static bool TryParseVersion(string s, out Version v)
		{
			v = null;
			if (string.IsNullOrEmpty(s))
				return false;
			var m = McVersionRegex.Match(s);
			if (!m.Success)
				return false;
			return Version.TryParse(m.Value, out v);
		}

		private static bool UsesNewSchema(Version v)
		{
			return v >= NewSchemaVersion;
		}

		/// <summary>
		/// 按 MC 版本区间映射 pack_format（资源包）。
		/// 数值参考 Minecraft Wiki 的 Pack format 表。
		/// </summary>
		private static int FormatFor(Version v)
		{
			if (v < new Version(1, 9)) return 1;        // 1.6.1–1.8.9
			if (v < new Version(1, 11)) return 2;       // 1.9–1.10.2
			if (v < new Version(1, 13)) return 3;       // 1.11–1.12.2
			if (v < new Version(1, 15)) return 4;       // 1.13–1.14.4
			if (v < new Version(1, 16, 2)) return 5;    // 1.15–1.16.1
			if (v < new Version(1, 17)) return 6;       // 1.16.2–1.16.4
			if (v < new Version(1, 18)) return 7;       // 1.17–1.17.1
			if (v < new Version(1, 18, 2)) return 8;    // 1.18–1.18.1
			if (v < new Version(1, 19, 3)) return 9;    // 1.18.2–1.19.2
			if (v < new Version(1, 19, 4)) return 12;   // 1.19.3
			if (v < new Version(1, 20)) return 13;      // 1.19.4
			if (v < new Version(1, 20, 2)) return 15;   // 1.20–1.20.1
			if (v < new Version(1, 20, 3)) return 18;   // 1.20.2
			if (v < new Version(1, 20, 5)) return 22;   // 1.20.3–1.20.4
			if (v < new Version(1, 21)) return 32;      // 1.20.5–1.20.6
			if (v < new Version(1, 21, 2)) return 34;   // 1.21–1.21.1
			if (v < new Version(1, 21, 4)) return 42;   // 1.21.2–1.21.3
			if (v < new Version(1, 21, 5)) return 46;   // 1.21.4
			if (v < new Version(1, 21, 6)) return 55;   // 1.21.5
			if (v < new Version(1, 21, 7)) return 63;   // 1.21.6
			if (v < new Version(1, 21, 9)) return 64;   // 1.21.7–1.21.8
			return NewSchemaMinFormat;                  // 1.21.9+（实际走新 schema）
		}

		/// <summary>
		/// 在指定目录生成 pack.mcmeta（目录不存在时自动创建）。
		/// 1.21.8 及以下写 pack_format；1.21.9 起写 min_format / max_format。
		/// </summary>
		public static void Generate(string outputDir, string mcVersion, string description = DefaultDescription)
		{
			if (string.IsNullOrEmpty(outputDir))
				return;

			Directory.CreateDirectory(outputDir);

			Version v = TryParseVersion(mcVersion, out Version parsed) ? parsed : new Version(1, 20, 1);

			string json;
			if (UsesNewSchema(v))
			{
				// 1.21.9+：pack_format / supported_formats 已废弃，改填 min_format / max_format 区间
				json = JsonConvert.SerializeObject(new
				{
					pack = new
					{
						min_format = NewSchemaMinFormat,
						max_format = NewSchemaMinFormat,
						description = description
					}
				}, Formatting.Indented);
			}
			else
			{
				json = JsonConvert.SerializeObject(new
				{
					pack = new
					{
						pack_format = FormatFor(v),
						description = description
					}
				}, Formatting.Indented);
			}

			File.WriteAllText(Path.Combine(outputDir, "pack.mcmeta"), json);
		}
	}
}
